IMPORTING REQUIRED LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

IMPORTING DATASET INTO VARIABLE USING PANDAS


In [2]:
dataset = pd.read_csv("Data.csv")

SEPERATING X AND Y FEATURES IN ORDER TO MAP

In [3]:
X = dataset.iloc[:,:-1].values         # X is know as features
Y = dataset.iloc[:,-1].values          # Y is knows as labels

iloc means index location and helps to select all features x and result y 


TALKING CARE OF MISSING DATA

In [4]:
from sklearn.impute import SimpleImputer                                   #library used to deal with missing data
imputer = SimpleImputer()                                                  #created an instance of the class simpleimputer 
imputer  = SimpleImputer(missing_values = np.nan , strategy = "mean")
imputer.fit(X[:,1:3])                                                      #fitting means to train the data set and calculate things such as deviation
X[:,1:3] = imputer.transform(X[:,1:3])                                     #to change the actual values we use transfrom

DEALING WITH CATEGORICAL VALUES SUCH AS COUNTRY NAME

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 
#we will use these to libraries for encoding categorical values

we are using one hot encoder as out encoding and only transforming the first column 

In [6]:
ct = ColumnTransformer(transformers = [("encoding",OneHotEncoder(),[0])],remainder = "passthrough")   #passthrough will copy remaining features as it is
X = np.array(ct.fit_transform(X))
print(X)             #as u can see the country column is succesfully encoded

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


now we will encode our label(Y) from yess no to numbers

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 
Y = le.fit_transform(Y)         #and we are done with categorical encoding !!

SPLITTING DATA INTO TRAIN AND TEST SET

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 1)   

FEATURE SCALING

now for scaling we have two procedures 
STANDARDIZATION - useful in every case         --we will only learn to do this
NORMALIZATION - useful onlt in cases where values are normalized

stndr = x - mean(x)/standard deviation(x)       ranges from -3 to +3

norml = x - min(x)/max(x) - min(x)              ranges from 0 to 1


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [10]:
X_test[:,3:] = sc.transform(X_test[:,3:])
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
