In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__
tf.config.experimental.list_physical_devices()
tf.config

<module 'tensorflow._api.v2.config' from 'c:\\Users\\Gaurav Arora\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tensorflow\\_api\\v2\\config\\__init__.py'>

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder="passthrough")
x = ct.fit_transform(x)

In [6]:
print(x)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [9]:
ann = tf.keras.models.Sequential()


In [10]:
ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

In [11]:
ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

In [12]:

ann.add(tf.keras.layers.Dense(units = 1,activation = "sigmoid"))


In [13]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [14]:
with tf.device("/cpu:0"):
    ann.fit(x_train, y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 0s 864us/step - loss: 0.6224 - accuracy: 0.7492
Epoch 2/200
250/250 [==============================] - 0s 854us/step - loss: 0.5036 - accuracy: 0.7961
Epoch 3/200
250/250 [==============================] - 0s 851us/step - loss: 0.4566 - accuracy: 0.8006
Epoch 4/200
250/250 [==============================] - 0s 847us/step - loss: 0.4351 - accuracy: 0.8100
Epoch 5/200
250/250 [==============================] - 0s 851us/step - loss: 0.4245 - accuracy: 0.8185
Epoch 6/200
250/250 [==============================] - 0s 875us/step - loss: 0.4181 - accuracy: 0.8231
Epoch 7/200
250/250 [==============================] - 0s 841us/step - loss: 0.4134 - accuracy: 0.8248
Epoch 8/200
250/250 [==============================] - 0s 835us/step - loss: 0.4089 - accuracy: 0.8289
Epoch 9/200
250/250 [==============================] - 0s 827us/step - loss: 0.4046 - accuracy: 0.8280
Epoch 10/200
250/250 [==============================] - 0s 831us/step - l

In [15]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 1s 1s/step
[[False]]


In [16]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

63/63 [==============================] - 0s 2ms/step


0.857