In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__
tf.config.experimental.list_physical_devices()
tf.config

<module 'tensorflow._api.v2.config' from 'c:\\Users\\Gaurav Arora\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tensorflow\\_api\\v2\\config\\__init__.py'>

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder="passthrough")
x = ct.fit_transform(x)

In [6]:
print(x)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [9]:
ann = tf.keras.models.Sequential()


In [10]:
ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

In [11]:
ann.add(tf.keras.layers.Dense(units = 6,activation = "relu"))

In [12]:

ann.add(tf.keras.layers.Dense(units = 1,activation = "sigmoid"))


In [13]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [18]:
with tf.device("/cpu:0"):
    ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3514 - accuracy: 0.8574
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3495 - accuracy: 0.8570
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3481 - accuracy: 0.8569
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3474 - accuracy: 0.8579
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3464 - accuracy: 0.8584
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3457 - accuracy: 0.8601
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3448 - accuracy: 0.8596
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3440 - accuracy: 0.8601
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3438 - accuracy: 0.8610
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3427 - accura

In [19]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 52ms/step
[[False]]


In [20]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

63/63 [==============================] - 0s 2ms/step


0.861