In [12]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [13]:
dataset = pd.read_csv("Data.csv")

In [14]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

ASSUMPTIONS OF LINEAR REGRESSION
1)linearity
2)Homoscedasticity
3)Multivariate normality
4)Independence of errors
5)Lack of multicolinearity

In [4]:
from sklearn.compose import ColumnTransformer

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [6]:
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[3])],remainder = 'passthrough')

In [7]:
X = np.array(ct.fit_transform(X))

In [15]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
lt = LinearRegression()

In [20]:
lt.fit(X_train,Y_train)

LinearRegression()

In [21]:
Y_pred = lt.predict(X_test)

In [22]:
np.set_printoptions(precision  = 2)      #2 decimal places
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))


[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


In [36]:
print(lt.predict([[1, 0, 0, 160000, 130000, 300000]]))

[181566.92]


In [37]:
print(lt.coef_)
print(lt.intercept_)

[ 8.66e+01 -8.73e+02  7.86e+02  7.73e-01  3.29e-02  3.66e-02]
42467.52924854249
